### ISSUE TITLE
How can I save the model?

### ISSUE THREAD

**Issue by Haobo-Liu** [hyperzy/SDF-2-SDF#1]

**Comment by hyperzy** [comment]
My apology for the late reply. Just leave a comment here for references.

An easier way to save the model will be adding a method in the Displayer class, whereby one could use instantiate a `vtkPLYWriter` and setup the data source and the writing destination. E.g.
```
auto ply_writer  = vtkSmartPointer<vtkPLYWriter>::New();
ply_writer->SetFileName(dst_path.c_str());
ply_writer->SetInputConnection(iso_surfaces["ref"]->GetOutputPort());
ply_writer->Write();
```

**Comment by Haobo-Liu** [comment]
Thanks a lot for your reply!



---Original---
From: ***@***.***&gt;
Date: Mon, Sep 25, 2023 12:35 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [hyperzy/SDF-2-SDF] How can I save the model? (Issue #1)




 
My apology for the late reply. Just leave a comment here for references.
 
An easier way to save the model will be adding a method in the Displayer class, whereby one could use instantiate a vtkPLYWriter and setup the data source and the writing destination. E.g.
 auto ply_writer  = vtkSmartPointer<vtkPLYWriter&gt;::New(); ply_writer-&gt;SetFileName(dst_path.c_str()); ply_writer-&gt;SetInputConnection(iso_surfaces["ref"]-&gt;GetOutputPort()); ply_writer-&gt;Write();
